### PR TITLE
Support VT codes in Windows

### PR DESCRIPTION
**Pull request by chrycheng**

### CODE REVIEW

**Comment by sambrightman** [comment]
Can you provide some context on what this PR is trying to achieve? Is this for coloured output from tests?

**Comment by chrycheng** [comment]
Sorry, yes, that's correct.  It enables the [Windows console to interpret virtual terminal sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences).  Without it, they would appear as plain characters on screen like so:

uninterpreted-vt-codes

They should appear colored like so:

interpreted-vt-codes

**Comment by Fuco1** [comment]
I don't see any problem with merging this.  WDYT?  Worst case we break the 3 windows users who run Emacs there :)

**Comment by jcs090218** [comment]
Does this appear in powershell? If this works in powershell then I might pass this PR.

**Pull request closed without merging**
