### PR TITLE
Add CELPA to source

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by conao3** [comment]
LGTM. Please clean commit history?

**Comment by jcs090218** [comment]
I think squash and merge should be good? :)

**Comment by conao3** [comment]
Sorry, I don't like squash merge, please create separate merge commit next time!

**Comment by jcs090218** [comment]
> I don't like squash merge

Hmm... Is there a reason why not? But yes, I can do that next time.

**Pull request merged**
