### PR TITLE
Fix emacs command

### PR DESCRIPTION
**Pull request by phillord**
Fix Broken logic in the command line handling, add ecukes test.

What could go wrong? Well, in the last tweaks to my PR, it appears I copied one fix wrong, did not check it was working, and had no tests to pick the issue up either.

10 out of 10 for style, minus several million for good thinking.

### CODE REVIEW

**Comment by rejeep** [comment]
👍

**Comment by lunaryorn** [comment]
@phillord Thanks, merged.

Minus a million for me, too, for not spotting this in the review 😥

**Comment by phillord** [comment]
@lunaryorn Guess you assumed I was capable of cutting and pasting! No worries, all done.

**Comment by lunaryorn** [comment]
@phillord  Thanks :relaxed: :+1:

**Pull request merged**
