### PR TITLE
Add Cask to auto-mode-alist

### PR DESCRIPTION
**Pull request by zonuexe**
Edit `Cask` file using `lisp-mode`

### CODE REVIEW

**Comment by lunaryorn** [comment]
@zonuexe This doesn't belong into `cask.el`.  It's a non-interactive library, and generally Cask is a non-interactive tool.  Closing as wontfix.

**Comment by rejeep** [comment]
@zonuexe You could instead update the documentation with a recommendation on adding that line to the Emacs configuration. I would recommend adding it on the [Cask DSL page](http://cask.readthedocs.org/en/latest/guide/dsl.html).

**Comment by zonuexe** [comment]
@rejeep It is a good idea.  But, casual users may not read the document...

I know that Cask is not an interactive application. I also know that it is loaded from  batch-mode.
This line maybe don't interfere with Cask.  And, it will help to casual users.

**Comment by rejeep** [comment]
Well, casual users will not add `cask` to their Emacs configuration, which would be necessary for this to load.

**Pull request closed without merging**
